# Generated by Django 2.2.10 on 2020-10-06 12:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('category_name', models.CharField(max_length=100)),
                ('music_main', models.FileField(default=None, upload_to='uploads/sound', validators=[django.core.validators.FileExtensionValidator(['mp3', 'mp4', 'acc'])], verbose_name='添付音声ファイル')),
            ],
        ),
    ]
