# Generated by Django 2.2.10 on 2020-10-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platForm', '0002_contents_foo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='foo',
            field=models.IntegerField(choices=[(1, 'foo1'), (2, 'foo2')], default='SOME STRING'),
        ),
    ]
