# Generated by Django 2.2.10 on 2020-10-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platForm', '0004_auto_20201020_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='foo',
        ),
    ]
